version: '3'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    environment:
    - FLASK_APP=app/run.py
    ports:
    - "5000:5000"
    links:
    - redis
  redis:
    image: redis

  unittest:
    build: .
    command: python3 -m unittest -v